
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-DXB-W7rAPkrzHBW-wSSrmihYZkigGaM',
    appId: '1:766732878424:web:08c70e14c1ff1322bec02d',
    messagingSenderId: '766732878424',
    projectId: 'kdu-transportation-service',
    authDomain: 'kdu-transportation-service.firebaseapp.com',
    storageBucket: 'kdu-transportation-service.appspot.com',
    measurementId: 'G-VF026CBFT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB_7Upmc0VZ7jTRxh-EQlYaV2n1ST2sLE',
    appId: '1:766732878424:android:90e683b9103c6f8bbec02d',
    messagingSenderId: '766732878424',
    projectId: 'kdu-transportation-service',
    storageBucket: 'kdu-transportation-service.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO_3BPYKGbo5tc0F9rgzIwoj5U-cOamNk',
    appId: '1:766732878424:ios:48e8ae0d31659865bec02d',
    messagingSenderId: '766732878424',
    projectId: 'kdu-transportation-service',
    storageBucket: 'kdu-transportation-service.appspot.com',
    iosBundleId: 'com.example.eShuttle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO_3BPYKGbo5tc0F9rgzIwoj5U-cOamNk',
    appId: '1:766732878424:ios:48e8ae0d31659865bec02d',
    messagingSenderId: '766732878424',
    projectId: 'kdu-transportation-service',
    storageBucket: 'kdu-transportation-service.appspot.com',
    iosBundleId: 'com.example.eShuttle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-DXB-W7rAPkrzHBW-wSSrmihYZkigGaM',
    appId: '1:766732878424:web:0feb8b2d9a1f5c6fbec02d',
    messagingSenderId: '766732878424',
    projectId: 'kdu-transportation-service',
    authDomain: 'kdu-transportation-service.firebaseapp.com',
    storageBucket: 'kdu-transportation-service.appspot.com',
    measurementId: 'G-9RFHY2Q9SY',
  );

}